# Generated by Django 5.1.6 on 2025-03-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_recipesteps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipesteps",
            options={
                "ordering": ["order"],
                "verbose_name": "Recipe Step",
                "verbose_name_plural": "Recipe Steps",
            },
        ),
        migrations.RemoveField(
            model_name="recipesteps",
            name="user",
        ),
        migrations.AlterField(
            model_name="recipesteps",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="api.recipe",
            ),
        ),
    ]
