# Generated by Django 5.1.6 on 2025-03-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_recipesteps_options_remove_recipesteps_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="recipesteps",
            name="order",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
