# Generated by Django 5.1.6 on 2025-03-12 20:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_recipe_description_alter_recipesteps_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.DecimalField(
                choices=[
                    (0.0, "0.0"),
                    (0.5, "0.5"),
                    (1.0, "1.0"),
                    (1.5, "1.5"),
                    (2.0, "2.0"),
                    (2.5, "2.5"),
                    (3.0, "3.0"),
                    (3.5, "3.5"),
                    (4.0, "4.0"),
                    (4.5, "4.5"),
                    (5.0, "5.0"),
                ],
                decimal_places=1,
                default=0.0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="reviewed_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        choices=[
                            (0.5, "0.5"),
                            (1.0, "1.0"),
                            (1.5, "1.5"),
                            (2.0, "2.0"),
                            (2.5, "2.5"),
                            (3.0, "3.0"),
                            (3.5, "3.5"),
                            (4.0, "4.0"),
                            (4.5, "4.5"),
                            (5.0, "5.0"),
                        ],
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "recipe"),
                        name="unique_review_per_user_per_recipe",
                    )
                ],
            },
        ),
    ]
