# Generated by Django 5.1.6 on 2025-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_ingredients_userprofile_ownedingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredientType',
            field=models.CharField(choices=[('fruitsVegetables', 'Fruits & Vegetables'), ('protein', 'Protein'), ('grains', 'Grains'), ('dairy', 'Dairy'), ('herbsSpices', 'Herbs & Spices'), ('other', 'Other')], default='N/A', max_length=30),
        ),
    ]
