# Generated by Django 5.1.6 on 2025-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_ingredient_ingredienttype_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "ingredientType"), name="unique_ingredient_name_type"
            ),
        ),
    ]
