# Generated by Django 5.1.6 on 2025-03-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_recipecomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="api.recipecomponent",
            ),
        ),
    ]
