# Generated by Django 5.1.6 on 2025-03-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_recipeingredient_recipe_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.recipecomponent'),
        ),
    ]
