# Generated by Django 5.1.6 on 2025-03-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_recipeingredient_recipe_component"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipecomponent",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="recipecomponent",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
