# Generated by Django 5.1.6 on 2025-04-10 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_review_dislikedby_review_dislikes_review_likedby_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="buyIngredients",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favouriteRecipes",
            field=models.ManyToManyField(
                blank=True, related_name="favourite_to", to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="dislikes",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="likes",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
