# Generated by Django 5.1.6 on 2025-04-12 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_userprofile_buyingredients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friendsList",
            field=models.ManyToManyField(
                blank=True, related_name="friends_with", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
