# Generated by Django 5.1.6 on 2025-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_userprofile_friendslist"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profilePicture",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profilePicture/"
            ),
        ),
    ]
