# Generated by Django 5.1.6 on 2025-06-28 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_image_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="dislikes",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="likes",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
