# Generated by Django 5.1.6 on 2025-06-28 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_review_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe_image_url",
            new_name="recipeImageUrl",
        ),
    ]
