name: Chefify CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-backend:
        name: Django Tests
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: chefify_test
                ports: ["5432:5432"]
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/chefify_test

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install -r chefify_backend/requirements.txt

            - name: Run Django Tests
              run: |
                  python chefify_backend/manage.py test

    test-frontend:
        name: React Build Check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install frontend dependencies
              working-directory: chefify_react
              run: npm install

            - name: Run frontend build
              working-directory: chefify_react
              run: npm run build
