# Generated by Django 5.0.6 on 2024-06-05 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_recipe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cuisine",
            new_name="Categories",
        ),
    ]
