# Generated by Django 5.0.6 on 2024-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_rename_cuisine_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
