# Generated by Django 5.0.6 on 2024-06-06 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_categories_name_alter_ingredient_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cuisine",
            new_name="Categories",
        ),
    ]
