# Generated by Django 5.0.6 on 2024-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_profile_user_ingredients_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_recipe_list",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_recipe_list",
            field=models.ManyToManyField(blank=True, to="base.recipe"),
        ),
    ]
