# Generated by Django 5.0.6 on 2024-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_profile_user_recipe_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
