# Generated by Django 5.0.6 on 2024-06-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_recipe_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_name',
            new_name='culinarian',
        ),
    ]
