# Generated by Django 5.0.6 on 2024-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_rename_cook_name_recipe_culinarian"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="guide",
            field=models.TextField(blank=True),
        ),
    ]
