# Generated by Django 5.0.6 on 2024-06-11 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_shoppinglist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShoppingList",
        ),
    ]
