# Generated by Django 5.0.6 on 2024-06-11 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_shoppinglist"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.ingredient",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.shoppinglist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="shopping_lists",
                through="base.IngredientShoppingList",
                to="base.ingredient",
            ),
        ),
    ]
