# Generated by Django 5.0.6 on 2024-06-11 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_ingredientshoppinglist_shoppinglist_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
