# Generated by Django 5.0.6 on 2024-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_shoppinglist_created_shoppinglist_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                related_name="shopping_lists",
                through="base.IngredientShoppingList",
                to="base.ingredient",
            ),
        ),
    ]
