# Generated by Django 5.0.6 on 2024-06-14 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0023_alter_shoppinglist_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="steps",
            old_name="author",
            new_name="user",
        ),
    ]
