# Generated by Django 5.0.6 on 2024-06-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0024_rename_author_steps_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients_list",
        ),
        migrations.CreateModel(
            name="IngredientUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                            ("cup", "Cup"),
                            ("oz", "Ounce"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("ml", "Milliliter"),
                            ("l", "Liter"),
                            ("p", "Pinch"),
                            ("d", "Dash"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="base.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeComponents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "ingredients_list",
                    models.ManyToManyField(
                        blank=True, null=True, to="base.ingredientunit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_components_list",
            field=models.ManyToManyField(
                blank=True, null=True, to="base.recipecomponents"
            ),
        ),
    ]
