# Generated by Django 5.0.6 on 2024-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_remove_recipe_ingredients_list_ingredientunit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientunit",
            name="unit",
            field=models.CharField(
                choices=[
                    ("tbsp", "Tablespoon"),
                    ("tsp", "Teaspoon"),
                    ("cup", "Cup"),
                    ("oz", "Ounce"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("ml", "Milliliter"),
                    ("L", "Liter"),
                    ("pinch", "Pinch"),
                    ("dash", "Dash"),
                ],
                max_length=15,
            ),
        ),
    ]
