# Generated by Django 5.0.6 on 2024-06-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_alter_ingredientunit_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
