# Generated by Django 5.0.6 on 2024-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0027_recipe_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="private",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="publish",
        ),
        migrations.AddField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("friends-only", "Friends Only"),
                ],
                default="private",
                max_length=15,
            ),
        ),
    ]
